#!/bin/bash

if [ $# -lt 1 ]; then
  >&2 echo "Usage: $0 [extra valgrind args] <test name>"
  exit 1
fi

args=""
prev=""

for arg in "$@"; do
  args="$args $prev"
  prev="$arg"
done

valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all $args ./$prev
